"""
ETI frame and file metadata.

Per Phase 3 of Enhanced ETI Output (Priority 5.5).
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class EtiMetadata:
    """
    Metadata for ETI frame or file.

    Note: ETI binary format doesn't support embedded metadata.
    This metadata can be:
    1. Written to companion .txt or .json file
    2. Logged for archival purposes
    3. Added to FRAMED format header (future enhancement)
    """
    creation_time: datetime = field(default_factory=lambda: datetime.now())
    generator: str = "python-dabmux"
    version: str = "0.7.0"
    ensemble_id: int = 0
    ensemble_label: str = ""
    ensemble_ecc: int = 0
    transmission_mode: int = 1
    source: str = ""  # e.g., "file", "udp", "tcp"
    format: str = "standard"  # "standard" or "ni"
    tist_enabled: bool = False
    frame_count: Optional[int] = None

    def to_comment(self) -> str:
        """
        Generate human-readable comment string.

        Returns:
            Multi-line comment string
        """
        lines = [
            f"Generated by {self.generator} v{self.version}",
            f"Created: {self.creation_time.isoformat()}",
            f"Ensemble: {self.ensemble_label} (0x{self.ensemble_id:04X}, ECC 0x{self.ensemble_ecc:02X})",
            f"Mode: {self.transmission_mode}",
            f"Format: ETI-{self.format.upper()}",
        ]

        if self.tist_enabled:
            lines.append("TIST: Enabled")

        if self.source:
            lines.append(f"Source: {self.source}")

        if self.frame_count is not None:
            lines.append(f"Frames: {self.frame_count}")

        return "\n".join(lines)

    def to_dict(self) -> dict:
        """
        Convert to dictionary for JSON serialization.

        Returns:
            Dictionary representation of metadata
        """
        return {
            'creation_time': self.creation_time.isoformat(),
            'generator': self.generator,
            'version': self.version,
            'ensemble': {
                'id': f"0x{self.ensemble_id:04X}",
                'label': self.ensemble_label,
                'ecc': f"0x{self.ensemble_ecc:02X}",
                'mode': self.transmission_mode
            },
            'format': self.format,
            'tist_enabled': self.tist_enabled,
            'source': self.source,
            'frame_count': self.frame_count
        }

    @classmethod
    def from_ensemble(cls, ensemble, frame_count: Optional[int] = None) -> 'EtiMetadata':
        """
        Create metadata from ensemble configuration.

        Args:
            ensemble: DabEnsemble instance
            frame_count: Number of frames (if known)

        Returns:
            EtiMetadata instance
        """
        return cls(
            ensemble_id=ensemble.id,
            ensemble_label=ensemble.label.text,
            ensemble_ecc=ensemble.ecc,
            transmission_mode=int(ensemble.transmission_mode),
            format="ni" if hasattr(ensemble, 'eti_format') and ensemble.eti_format == 'ni' else "standard",
            tist_enabled=ensemble.enable_tist,
            frame_count=frame_count
        )
